"""add name for token families

Revision ID: 0e04539fed93
Revises: 7d3bf6b557b7
Create Date: 2026-03-09 20:22:58.475945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e04539fed93'
down_revision: Union[str, Sequence[str], None] = '7d3bf6b557b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_family_names',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['refresh_tokens.family_id'], ),
    sa.PrimaryKeyConstraint('family_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_family_names')
    # ### end Alembic commands ###
