"""migrate to token hash

Revision ID: 4b47d2f27d89
Revises: 97993e17b5a5
Create Date: 2026-03-09 19:54:28.404766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b47d2f27d89"
down_revision: Union[str, Sequence[str], None] = "97993e17b5a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "token_hash", sa.String(length=255), nullable=False, server_default="0"
            )
        )
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_id"))
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_hash"), ["token_hash"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_hash"))
        batch_op.create_index(batch_op.f("ix_refresh_tokens_id"), ["id"], unique=False)
        batch_op.drop_column("token_hash")

    # ### end Alembic commands ###
