"""refresh token family and is_revoked

Revision ID: 97993e17b5a5
Revises: 9a5f2d3817c4
Create Date: 2026-03-09 17:58:28.497951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97993e17b5a5"
down_revision: Union[str, Sequence[str], None] = "9a5f2d3817c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "family_id",
                sa.Uuid(),
                nullable=False,
                server_default="00000000-0000-0000-0000-000000000000",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_revoked",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_family_id"), ["family_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_family_id"))
        batch_op.drop_column("is_revoked")
        batch_op.drop_column("family_id")

    # ### end Alembic commands ###
