#!/usr/bin/env bash
# setup-sops.sh
#only needed to be done once
#done by quinten

set -euo pipefail

TEAM_MEMBERS=(
  "c0ffeeadd1c7"
  "Johk3"
  "gabrielmeleiro1"
  "koevoet1221"
  "AlexKoops"
  "QuintoniusB"
  "jortvanleenen"
)

SOPS_CONFIG=".sops.yaml"
AGE_KEYS=()

echo "=== SOPS Setup: Fetching SSH keys and converting to age ==="
echo ""

for username in "${TEAM_MEMBERS[@]}"; do
  echo "Fetching SSH keys for ${username}..."
  ssh_keys=$(curl -sf "https://github.com/${username}.keys" 2>/dev/null || true)

  if [ -z "$ssh_keys" ]; then
    echo "  WARNING: No SSH keys found for ${username}. Skipping."
    continue
  fi

  # Take the first ed25519 key, or fall back to the first key
  ed25519_key=$(echo "$ssh_keys" | grep "ssh-ed25519" | head -n 1)
  if [ -n "$ed25519_key" ]; then
    key_to_convert="$ed25519_key"
  else
    key_to_convert=$(echo "$ssh_keys" | head -n 1)
  fi

  age_key=$(echo "$key_to_convert" | ssh-to-age 2>/dev/null || true)

  if [ -z "$age_key" ]; then
    echo "  WARNING: Could not convert SSH key for ${username} to age key."
    echo "  Note: ssh-to-age only supports ed25519 keys."
    continue
  fi

  echo "  Age key: ${age_key}"
  AGE_KEYS+=("$age_key")
done

echo ""

if [ ${#AGE_KEYS[@]} -eq 0 ]; then
  echo "ERROR: No age keys could be generated. Ensure team members have ed25519 SSH keys on GitHub."
  exit 1
fi

# Build the comma-separated age key string
AGE_RECIPIENTS=$(IFS=','; echo "${AGE_KEYS[*]}")

# Write .sops.yaml
cat > "$SOPS_CONFIG" << EOF
# SOPS Configuration — AUTO-GENERATED by setup-sops.sh
# Do not edit the age keys manually; re-run this script instead.

creation_rules:
  - path_regex: \.env\.enc\$
    age: >-
      ${AGE_RECIPIENTS}
EOF

echo "Written ${#AGE_KEYS[@]} age keys to ${SOPS_CONFIG}"
echo ""
echo "Next steps:"
echo "  1. Create your .env file with your secrets"
echo "  2. Encrypt it:  sops -e .env > .env.enc"
echo "  3. Commit .env.enc and .sops.yaml (NOT .env)"
echo ""
echo "Done!"
